import { Platform, StyleSheet } from 'react-native';
import { shadows } from '../../utils/shadows';

const baseStyles = {
  container: {
    flex: 1,
    backgroundColor: "#F4F7FC",
    paddingHorizontal: 0,
  },
  // Parent-like header styles
  parentLikeHeaderContainer: {
    paddingTop: 40,
    paddingBottom: 8,
    paddingHorizontal: 2,
  },
  parentLikeHeaderGradient: {
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  logoImage: {
    width: 60,
    height: 80,
  },
  headerBadge: {
    backgroundColor: '#e3f2fd',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 8,
    alignSelf: 'flex-start',
  },
  headerBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#2196f3',
  },
  headerActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    flexShrink: 0,
    maxWidth: 160,
    justifyContent: 'flex-end',
  },
  headerButton: {
    padding: 6,
    marginLeft: 4,
    marginBottom: 4,
    minWidth: 36,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    ...shadows.md,
  },
  profileHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  profileImageContainer: {
    position: "relative",
    marginRight: 16,
  },
  profileImage: {
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 2,
    borderColor: "#E5E7EB",
  },
  verifiedBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: "#10B981",
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#FFFFFF",
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: 18,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 4,
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  ratingText: {
    fontSize: 14,
    color: "#6B7280",
    marginLeft: 4,
  },
  profileDetail: {
    fontSize: 14,
    color: "#6B7280",
  },
  profileAge: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 2,
  },
  profileContact: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 2,
  },
  editProfileButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
  },
  tabs: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    marginTop: 16,
    marginHorizontal: 16,
    borderRadius: 12,
    padding: 4,
    ...shadows.sm,
  },
  tab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  navContainer: {
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  navScroll: {
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  navTab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginRight: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    minWidth: 100,
  },
  navTabActive: {
    backgroundColor: '#BED6FC',
    borderColor: '#BED6FC',
  },
  navTabText: {
    marginLeft: 8,
    fontSize: 14,
    fontWeight: '500',
    color: '#6B7280',
  },
  navTabTextActive: {
    color: '#3B83F5',
    fontWeight: '600',
  },
};

// UPDATED: Enhanced section styles with better typography and spacing
const sections = {
  section: {
    marginBottom: 28,
    paddingHorizontal: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  sectionHeaderMain: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1F2937',
    marginLeft: 8,
  },
  seeAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#3B82F6',
    marginRight: 4,
  },
  horizontalScroll: {
    marginTop: 12,
    paddingLeft: 4,
  },

  // UPDATED: Enhanced Profile Card with gradient and better styling
  enhancedProfileCard: {
    borderRadius: 16,
    marginHorizontal: 16,
    marginVertical: 8,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  enhancedProfileContent: {
    padding: 20,
  },
  enhancedProfileHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  enhancedProfileIcon: {
    marginRight: 12,
    marginTop: 2,
  },
  enhancedProfileText: {
    flex: 1,
  },
  enhancedProfileTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  enhancedProfileDescription: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.9)',
    lineHeight: 20,
  },
  enhancedProfileButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  enhancedProfileButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginRight: 8,
  },
};

const dashboard = {
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  quickGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    marginBottom: 16,
    gap: 12,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    marginBottom: 24,
    gap: 12,
  },
  quickTile: {
    width: '48%',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F3F4F6',
    ...shadows.sm,
  },
  quickTileInteractive: {
    borderColor: '#BFDBFE',
  },
  quickTilePressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.95,
  },
  quickActionTile: {
    width: '48%',
    borderRadius: 16,
    ...shadows.md,
  },
  quickActionContent: {
    overflow: 'hidden',
    borderRadius: 16,
  },
  quickActionGradient: {
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    minHeight: 100,
    justifyContent: 'center',
  },
  quickIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  quickActionIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  quickValue: {
    fontSize: 24,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 4,
    lineHeight: 28,
    textAlign: 'center',
  },
  statCard: {
    width: '31%',
    borderRadius: 12,
    padding: 16,
    ...shadows.xs,
  },
  statIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  statValue: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#6B7280',
  },
};

// UPDATED: Enhanced Application Cards with better styling
const cards = {
  // Enhanced Application Card Styles
  enhancedApplicationCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  applicationCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  applicationCardMain: {
    flex: 1,
    marginRight: 12,
  },
  applicationCardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 4,
  },
  applicationCardFamily: {
    fontSize: 14,
    color: '#6B7280',
  },
  applicationCardDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    flexWrap: 'wrap',
  },
  applicationDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 16,
    marginBottom: 4,
  },
  applicationDetailTextInline: {
    fontSize: 12,
    color: '#6B7280',
    marginLeft: 4,
  },
  applicationCardActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },

  // Original styles kept for compatibility
  applicationCard: {
    marginBottom: 12,
    borderRadius: 12,
    ...shadows.sm,
  },
  applicationContent: {
    padding: 16,
  },
  applicationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  applicationJobTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 2,
  },
  applicationFamily: {
    fontSize: 14,
    color: '#6B7280',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  statusText: {
    fontSize: 12,
    fontWeight: '500',
    marginLeft: 4,
  },
  statusIcon: {
    marginRight: 4,
  },
  applicationDetails: {
    marginBottom: 12,
  },
  applicationDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  applicationDetailTextList: {
    fontSize: 13,
    color: '#4B5563',
    marginLeft: 8,
  },
  applicationActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  applicationButton: {
    minWidth: 100,
  },
  applicationButtonText: {
    fontSize: 13,
    fontWeight: '500',
  },
  bookingCard: {
    marginBottom: 16,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F3F4F6',
    ...shadows.md,
  },
  bookingContent: {
    padding: 20,
  },
  bookingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  bookingTitleSection: {
    flex: 1,
    marginRight: 12,
  },
  bookingFamily: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
    lineHeight: 22,
  },
  bookingDate: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '500',
  },
  bookingDetails: {
    marginBottom: 20,
  },
  bookingDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  bookingDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  bookingDetailText: {
    fontSize: 14,
    color: '#4B5563',
    marginLeft: 8,
    fontWeight: '500',
  },
  bookingLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginLeft: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: '#F8FAFC',
  },
  bookingLocationText: {
    fontSize: 14,
    color: '#2563EB',
    fontWeight: '500',
    flex: 1,
  },
  locationIcon: {
    marginLeft: 6,
  },
  bookingActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    gap: 12,
  },
  bookingSecondaryButton: {
    flex: 1,
    borderColor: '#D1D5DB',
    borderRadius: 12,
    minHeight: 44,
  },
  bookingSecondaryButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  bookingPrimaryButton: {
    flex: 1,
    backgroundColor: '#2563EB',
    borderRadius: 12,
    minHeight: 44,
  },
  bookingPrimaryButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  bookingConfirmButton: {
    flex: 1,
    backgroundColor: '#059669',
    borderRadius: 12,
    minHeight: 44,
  },
  bookingConfirmButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  dashboardBookingCard: {
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
    ...shadows.md,
  },
  dashboardBookingHeader: {
    padding: 16,
  },
  dashboardBookingHeaderContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dashboardBookingTitleContainer: {
    flex: 1,
    marginRight: 12,
  },
  dashboardBookingTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  dashboardBookingSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.85)',
  },
  dashboardBookingStatusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
  },
  dashboardBookingStatusText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
    textTransform: 'capitalize',
  },
  dashboardBookingContent: {
    padding: 16,
    gap: 16,
  },
  dashboardBookingMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  dashboardBookingMetaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#EEF2FF',
  },
  dashboardBookingMetaText: {
    fontSize: 13,
    color: '#1F2937',
    flexShrink: 1,
  },
  dashboardBookingLocation: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
  },
  dashboardBookingLocationText: {
    flex: 1,
    fontSize: 13,
    color: '#1E3A8A',
  },
  dashboardBookingActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  dashboardBookingSecondaryButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  dashboardBookingSecondaryText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1F2937',
  },
  dashboardBookingPrimaryButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#2563EB',
  },
  dashboardBookingPrimaryText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  dashboardBookingConfirmButton: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#059669',
  },
  dashboardBookingConfirmText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
};

// UPDATED: Enhanced button styles for application cards
const buttons = {
  editProfileButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
  },
  secondaryButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D1D5DB',
  },
  secondaryButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#374151',
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: '#3B82F6',
  },
  primaryButtonDisabled: {
    backgroundColor: '#9CA3AF',
    opacity: 0.6,
  },
  primaryButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#FFFFFF',
    marginLeft: 4,
  },
};

const textBlocks = {
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: 18,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 4,
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  ratingText: {
    fontSize: 14,
    color: "#6B7280",
    marginLeft: 4,
  },
  profileDetail: {
    fontSize: 14,
    color: "#6B7280",
  },
  profileAge: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 2,
  },
  profileContact: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 2,
  },
};

const modals = {
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
};

const notification = {
  urgentBadge: {
    backgroundColor: '#FEE2E2',
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    alignSelf: 'flex-start',
  },
  urgentBadgeText: {
    color: '#DC2626',
    fontSize: 10,
    fontWeight: '600',
  },
};

const stateStyles = {
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 32,
  },
  loadingText: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 12,
  },
  settingLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: '#111827',
    flex: 1,
  },
  settingDesc: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 2,
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#374151',
    marginBottom: 8,
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: '#FFFFFF',
  },
  textInputDisabled: {
    backgroundColor: '#F9FAFB',
    opacity: 0.6,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
  },
  saveButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 16,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  sectionDivider: {
    height: 1,
    backgroundColor: '#F3F4F6',
    marginVertical: 16,
  },
  sectionSubtitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 12,
  },
  skillsSection: {
    marginBottom: 16,
  },
  skillsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  skillTag: {
    backgroundColor: '#EFF6FF',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
  },
  skillText: {
    color: '#2563EB',
    fontSize: 13,
    fontWeight: '500',
  },
  certificationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  certificationIcon: {
    marginRight: 12,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyStateText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginTop: 16,
    marginBottom: 4,
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    paddingHorizontal: 32,
  },
  filters: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
  },
  filterChip: {
    marginRight: 8,
    marginBottom: 8,
    backgroundColor: '#F3F4F6',
    borderRadius: 16,
  },
  filterChipActive: {
    backgroundColor: '#EFF6FF',
  },
  filterChipText: {
    color: '#6B7280',
    fontSize: 13,
    fontWeight: '500',
  },
  filterChipTextActive: {
    color: '#2563EB',
  },
  bookingFilterTabsContainer: {
    marginBottom: 16,
  },
  bookingFilterTabs: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 2,
  },
  bookingFilterTab: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginRight: 8,
    minHeight: 40,
    justifyContent: 'center',
  },
  activeBookingFilterTab: {
    backgroundColor: '#3B82F6',
    borderColor: '#1D4ED8',
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 4,
  },
  bookingFilterTabText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#4B5563',
    textAlign: 'center',
  },
  activeBookingFilterTabText: {
    color: '#FFFFFF',
  },
  bookingFilterTabCount: {
    color: '#1F2937',
    fontWeight: '500',
  },
  reviewsContainer: {
    flex: 1,
    backgroundColor: '#F9FAFB',
    padding: 2,
  },
  reviewsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 0,
    overflow: 'hidden',
    ...shadows.md,
  },
  reviewsHeroCard: {
    borderRadius: 18,
    padding: 20,
    marginBottom: 20,
    ...shadows.md,
  },
  reviewsHeroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reviewsHeroMetric: {
    flex: 1,
    marginRight: 16,
  },
  reviewsHeroLabel: {
    color: 'rgba(255,255,255,0.86)',
    fontSize: 13,
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  reviewsHeroValueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginTop: 8,
    gap: 6,
  },
  reviewsHeroValue: {
    fontSize: 40,
    fontWeight: '800',
    color: '#FFFFFF',
    lineHeight: 42,
  },
  reviewsHeroHint: {
    marginTop: 6,
    color: 'rgba(255,255,255,0.75)',
    fontSize: 12,
  },
  reviewsHeroButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    gap: 8,
  },
  reviewsHeroButtonText: {
    color: '#1D4ED8',
    fontWeight: '600',
    fontSize: 13,
  },
  reviewsFilterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 20,
    gap: 10,
  },
  reviewsFilterPill: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  reviewsFilterPillActive: {
    borderColor: '#FFFFFF',
    backgroundColor: '#FFFFFF',
  },
  reviewsFilterPillText: {
    color: 'rgba(255,255,255,0.86)',
    fontWeight: '600',
    fontSize: 12,
    letterSpacing: 0.2,
  },
  reviewsFilterPillTextActive: {
    color: '#1D4ED8',
  },
  reviewsSummaryGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  reviewsSummaryCard: {
    flex: 1,
    borderRadius: 14,
    padding: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    ...shadows.xs,
  },
  reviewsSummaryLabel: {
    fontSize: 13,
    color: '#1F2937',
    fontWeight: '600',
  },
  reviewsSummaryMetric: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
    marginTop: 8,
  },
  reviewsSummaryIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  reviewsSummaryValueRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 10,
  },
  reviewsSummaryValue: {
    fontSize: 28,
    fontWeight: '700',
    color: '#111827',
  },
  reviewsSummaryDetailIcon: {
    marginTop: 2,
  },
  reviewsSummaryDetailText: {
    flex: 1,
    fontSize: 12,
    fontWeight: '500',
    color: '#4B5563',
    lineHeight: 16,
  },
  reviewsBreakdownCard: {
    marginTop: 16,
    padding: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
  },
  reviewsBreakdownTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 12,
  },
  reviewsBreakdownRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    gap: 10,
  },
  reviewsBreakdownLabel: {
    width: 48,
    fontSize: 13,
    fontWeight: '600',
    color: '#1E293B',
  },
  reviewsBreakdownBar: {
    flex: 1,
    height: 10,
    borderRadius: 999,
    backgroundColor: '#E2E8F0',
    overflow: 'hidden',
  },
  reviewsBreakdownFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#1D4ED8',
  },
  reviewsBreakdownValue: {
    width: 32,
    textAlign: 'right',
    fontSize: 13,
    color: '#475569',
    fontWeight: '600',
  },
  reviewsContextBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 14,
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 12,
    backgroundColor: '#EEF2FF',
    borderWidth: 1,
    borderColor: '#DBEAFE',
  },
  reviewsContextText: {
    flex: 1,
    marginLeft: 12,
    color: '#1E3A8A',
    fontSize: 13,
    lineHeight: 18,
  },
  reviewsFooterCard: {
    marginTop: 20,
    padding: 18,
    borderRadius: 16,
    backgroundColor: '#E0EAFF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    shadowColor: '#1E3A8A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: Platform.select({ ios: 0.15, default: 0.1 }),
    shadowRadius: 10,
    elevation: 6,
    gap: 16,
  },
  reviewsFooterContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  reviewsFooterTextWrapper: {
    flex: 1,
  },
  reviewsFooterTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1E3A8A',
  },
  reviewsFooterSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: '#1E3A8A',
    opacity: 0.85,
    lineHeight: 18,
  },
  reviewsFooterButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#1D4ED8',
    gap: 8,
    shadowColor: '#1D4ED8',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: Platform.select({ ios: 0.2, default: 0.15 }),
    shadowRadius: 6,
    elevation: 4,
  },
  reviewsFooterButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  logoutButton: {
    margin: 16,
    backgroundColor: '#2563EB',
    borderRadius: 8,
  },
  logoutButtonText: {
    color: '#FFFFFF',
    fontWeight: '500',
  },
  // Badge shown when caregiver already applied to a job
  appliedBadge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: '#E8F5E9',
    borderColor: '#C8E6C9',
    borderWidth: 1,
    flexShrink: 1,
  },
  appliedBadgeContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  appliedBadgeText: {
    color: '#2E7D32',
    fontWeight: '600',
  },
  // Notification badge styles
  notificationBadge: {
    position: 'absolute',
    top: -6,
    right: -8,
    backgroundColor: '#ef4444',
    borderRadius: 12,
    minWidth: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
    zIndex: 10,
    paddingHorizontal: 2,
  },
  notificationBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 12,
    paddingHorizontal: 2,
  },
  // Modal overlay
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Loading states
  dashboardSkeletonContainer: {
    padding: 20,
    gap: 16,
  },
  dashboardSkeletonSummaryCard: {
    padding: 20,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
  },
  dashboardSkeletonSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  dashboardSkeletonSummaryInfo: {
    flex: 1,
    gap: 10,
  },
  dashboardSkeletonStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  dashboardSkeletonQuickStat: {
    flexBasis: '48%',
    padding: 18,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    gap: 8,
  },
  dashboardSkeletonActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  dashboardSkeletonAction: {
    flexBasis: '48%',
    padding: 16,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    gap: 8,
  },
  dashboardSkeletonSection: {
    padding: 18,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    gap: 14,
  },
  dashboardSkeletonItems: {
    gap: 12,
  },
  dashboardSkeletonItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  dashboardSkeletonItemInfo: {
    flex: 1,
    gap: 8,
  },
  // Application Modal Styles
  applicationModal: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    margin: 18,
    maxHeight: '88%',
    width: '92%',
    alignSelf: 'center',
    overflow: 'hidden',
    ...shadows.lg,
  },
  applicationModalScroll: {
    paddingBottom: 24,
  },
  applicationHeroGradient: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 18,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  applicationHeroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 10,
  },
  applicationStatusBadge: {
    alignSelf: 'flex-start',
  },
  applicationHeroContent: {
    flex: 1,
    gap: 8,
  },
  applicationHeroTitle: {
    fontSize: 19,
    lineHeight: 24,
    fontWeight: '700',
    color: '#F8FAFF',
  },
  applicationHeroSubtitle: {
    fontSize: 13,
    color: 'rgba(224, 231, 255, 0.85)',
  },
  applicationHeroMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 2,
    marginTop: 10,
  },
  applicationHeroMetaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.16)',
    gap: 6,
  },
  applicationHeroMetaText: {
    color: '#E0E7FF',
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 0.2,
  },
  applicationModalBody: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 12,
    gap: 10,
  },
  applicationModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  applicationModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
  },
  modalCloseButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  jobSummary: {
    padding: 10,
    backgroundColor: '#F8FAFC',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  jobSummaryTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 4,
  },
  jobSummaryFamily: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 8,
  },
  jobSummaryRate: {
    fontSize: 16,
    fontWeight: '600',
    color: '#059669',
  },
  applicationFormContainer: {
    padding: 20,
  },
  applicationInfoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  applicationInfoTile: {
    flexBasis: '48%',
    minWidth: 120,
    backgroundColor: '#F5F5FF',
    borderRadius: 16,
    padding: 16,
    gap: 8,
    borderWidth: 1,
    borderColor: '#E0E7FF',
  },
  applicationInfoLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4338CA',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  applicationInfoValue: {
    fontSize: 15,
    fontWeight: '500',
    color: '#1F2937',
  },
  applicationSection: {
    gap: 5,
  },
  applicationSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
  },
  applicationSectionCard: {
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  applicationSectionCardText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#374151',
  },
  applicationTagList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  applicationTagChip: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#EEF2FF',
  },
  applicationTagChipText: {
    fontSize: 12,
    color: '#4338CA',
    fontWeight: '500',
  },
  applicationInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: '#FFFFFF',
    color: '#111827',
    width: '100%',
    flex: 0,
  },
  applicationTextArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  applicationModalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    gap: 12,
  },
  highlightModalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    width: '92%',
    maxWidth: 480,
    maxHeight: '85%',
    paddingHorizontal: 20,
    paddingBottom: 20,
    ...shadows.lg,
  },
  highlightModalHeader: {
    paddingTop: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    marginBottom: 12,
  },
  highlightModalTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  highlightBody: {
    paddingBottom: 12,
  },
  highlightBodyContent: {
    paddingBottom: 24,
  },
  highlightSection: {
    marginBottom: 20,
  },
  highlightSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 6,
  },
  highlightSectionDescription: {
    fontSize: 13,
    color: '#6B7280',
    lineHeight: 18,
    marginBottom: 12,
  },
  highlightFamiliesList: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#F9FAFB',
  },
  highlightFamilyItem: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  highlightFamilyItemLast: {
    borderBottomWidth: 0,
  },
  highlightFamilySelected: {
    backgroundColor: '#EEF2FF',
  },
  highlightFamilyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  highlightFamilyInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 12,
  },
  highlightFamilyIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF2FF',
    marginRight: 12,
  },
  highlightFamilyText: {
    flex: 1,
  },
  highlightFamilyName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1F2937',
  },
  highlightFamilyMeta: {
    fontSize: 13,
    color: '#6B7280',
    marginTop: 2,
  },
  highlightHintBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#F3F4FF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E0E7FF',
    padding: 14,
  },
  highlightHintIcon: {
    marginRight: 12,
    marginTop: 2,
  },
  highlightHintText: {
    flex: 1,
    fontSize: 13,
    color: '#4338CA',
    lineHeight: 18,
  },
  highlightFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 16,
    marginTop: 12,
    paddingHorizontal: 4,
  },
  highlightFooterActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingVertical: 0,
    paddingHorizontal: 0,
    flexWrap: 'wrap',
    columnGap: 12,
    rowGap: 12,
  },
  highlightActionButton: {
    minWidth: 140,
  },
  highlightSecondaryButton: {
    borderRadius: 12,
    borderColor: '#D1D5DB',
  },
  highlightSecondaryLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1F2937',
  },
  highlightCancelButton: {
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  highlightCancelText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  highlightPrimaryButton: {
    backgroundColor: '#2563EB',
    borderRadius: 12,
    paddingVertical: 2,
    paddingHorizontal: 4,
  },
  highlightPrimaryContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  highlightPrimaryText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  highlightEmptyState: {
    alignItems: 'center',
    paddingVertical: 28,
    paddingHorizontal: 16,
    gap: 12,
  },
  highlightEmptyIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  highlightEmptyTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
  },
  highlightEmptySubtitle: {
    fontSize: 13,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 18,
  },
  cancelButton: {
    flex: 1,
    borderColor: '#D1D5DB',
  },
  submitButton: {
    flex: 1,
    backgroundColor: '#2563EB',
  },
  // Edit Profile Modal Styles
  editProfileModal: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    margin: 20,
    maxWidth: 400,
    width: '90%',
    alignSelf: 'center',
    ...shadows.lg,
  },
  editProfileTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 20,
    textAlign: 'center',
  },
  editProfileInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: '#FFFFFF',
    color: '#111827',
    marginBottom: 16,
  },
  editProfileSaveButton: {
    backgroundColor: '#2563EB',
    borderRadius: 8,
    marginBottom: 12,
  },
  editProfileSaveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  // Profile Card Styles
  profileCard: {
    marginBottom: 24,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    ...shadows.md,
  },
  profileImagePlaceholder: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#E5E7EB',
  },
  profileEmail: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 8,
  },
  profileStats: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  profileRate: {
    fontSize: 16,
    fontWeight: '700',
    color: '#059669',
    marginRight: 16,
  },
  profileExperience: {
    fontSize: 14,
    color: '#6B7280',
  },
  profileBio: {
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 20,
  },
  skillsPreview: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  skillsTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 8,
  },
  skillChip: {
    backgroundColor: '#EFF6FF',
    borderRadius: 16,
    marginRight: 8,
    marginBottom: 4,
  },
  skillChipText: {
    color: '#2563EB',
    fontSize: 12,
    fontWeight: '500',
  },
  moreSkillsText: {
    fontSize: 12,
    color: '#9CA3AF',
    alignSelf: 'center',
  },
  ageCarePreview: {
    marginTop: 12,
  },
  ageCareTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 4,
  },
  ageCareText: {
    fontSize: 14,
    color: '#4B5563',
  },
  editProfileSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    marginBottom: 20,
  },
  profileLocation: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 4,
  },
  certificationsPreview: {
    marginTop: 12,
  },
  certificationsTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 8,
  },
  certificationsContainer: {
    marginBottom: 8,
  },
  certificationText: {
    fontSize: 14,
    color: '#4B5563',
    marginBottom: 4,
  },
  moreCertificationsText: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  // Cover Letter Suggestions Styles
  suggestedCoverLettersContainer: {
    flexDirection: 'column',
    marginBottom: 16,
    gap: 8,
  },
  coverLetterChip: {
    backgroundColor: '#F3F4F6',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  coverLetterChipSelected: {
    backgroundColor: '#EFF6FF',
    borderColor: '#2563EB',
  },
  coverLetterChipText: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 18,
  },
  coverLetterChipTextSelected: {
    color: '#2563EB',
    fontWeight: '500',
  },
  // Cover Letter Display Styles
  coverLetterDisplay: {
    backgroundColor: '#F9FAFB',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginTop: 8,
  },
  coverLetterText: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
  },
  // Notification Styles
  notificationCard: {
    marginBottom: 12,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F3F4F6',
    ...shadows.sm,
  },
  notificationContent: {
    padding: 16,
  },
  notificationHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  notificationIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  notificationText: {
    flex: 1,
  },
  notificationTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 4,
  },
  unreadTitle: {
    fontWeight: '700',
    color: '#1F2937',
  },
  notificationMessage: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
    marginBottom: 4,
  },
  notificationTime: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  unreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#3B82F6',
    marginLeft: 8,
    marginTop: 4,
  },
  // Job Details Modal Styles
  jobDetailsModal: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    margin: 24,
    width: '92%',
    maxWidth: 420,
    alignSelf: 'center',
    overflow: 'hidden',
    ...shadows.lg,
  },
  jobDetailsContent: {
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 28,
    gap: 24,
  },
  jobDetailsHeader: {
    alignItems: 'center',
    gap: 10,
  },
  jobDetailsTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#0F172A',
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  jobDetailsFamily: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
  },
  jobDetailsInfo: {
    borderRadius: 20,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 16,
    gap: 12,
  },
  jobDetailsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  jobDetailsIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  jobDetailsText: {
    flex: 1,
    fontSize: 14,
    color: '#1F2937',
    lineHeight: 20,
  },
  jobDetailsPillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  jobDetailsPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#EEF2FF',
  },
  jobDetailsPillText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4338CA',
  },
  jobDetailsRequirements: {
    gap: 10,
  },
  jobDetailsRequirementsTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111827',
  },
  jobDetailsRequirementRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  jobDetailsRequirementText: {
    fontSize: 13,
    color: '#1F2937',
    flex: 1,
    lineHeight: 19,
  },
  jobDetailsActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    paddingTop: 8,
  },
  jobDetailsCloseButton: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
  },
  jobDetailsPrimaryButton: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: '#2563EB',
  },
  jobDetailsPrimaryLabel: {
    fontSize: 14,
    fontWeight: '600',
  },
  jobDetailsApplyButton: {
    flex: 1,
    backgroundColor: '#2563EB',
  },
  // Messaging and Reviews Styles
  messagesContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  chatContainer: {
    flex: 1,
  },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  backButton: {
    marginRight: 16,
  },
  chatTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#374151',
  },
  parentsList: {
    flex: 1,
  },
  parentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  parentInfo: {
    marginLeft: 12,
  },
  parentName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
  },
  parentStatus: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 2,
  },
  messagesList: {
    flex: 1,
    padding: 16,
  },
  messagesContent: {
    paddingBottom: 16,
  },
  messageBubble: {
    maxWidth: '80%',
    padding: 12,
    borderRadius: 16,
    marginBottom: 8,
  },
  currentUserMessage: {
    alignSelf: 'flex-end',
    backgroundColor: '#3B82F6',
  },
  otherUserMessage: {
    alignSelf: 'flex-start',
    backgroundColor: '#E5E7EB',
  },
  messageText: {
    fontSize: 16,
  },
  currentUserMessageText: {
    color: '#FFFFFF',
  },
  otherUserMessageText: {
    color: '#374151',
  },
  messageTime: {
    fontSize: 12,
    marginTop: 4,
    opacity: 0.7,
  },
  currentUserMessageTime: {
    color: '#FFFFFF',
    alignSelf: 'flex-end',
  },
  otherUserMessageTime: {
    color: '#6B7280',
    alignSelf: 'flex-start',
  },
  messageInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
  },
  messageInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginRight: 8,
    maxHeight: 100,
  },
  sendButton: {
    backgroundColor: '#3B82F6',
    borderRadius: 20,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  reviewerName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
  },
  reviewText: {
    fontSize: 14,
    color: '#4B5563',
    marginBottom: 8,
    lineHeight: 20,
  },
  reviewDate: {
    fontSize: 12,
    color: '#6B7280',
  },
  // Chat card styles
  chatHeaderCard: {
    margin: 8,
    marginBottom: 4,
    borderRadius: 12,
  },
  messagesCard: {
    flex: 1,
    margin: 8,
    marginVertical: 4,
    borderRadius: 12,
  },
  inputCard: {
    margin: 8,
    marginTop: 4,
    borderRadius: 12,
  },
  // Application Status Styles
  jobDetailsSection: {
    gap: 10,
  },
  jobDetailsSectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  jobDetailsDescription: {
    fontSize: 14,
    color: '#344155',
    lineHeight: 22,
  },
  applicationStatusCard: {
    backgroundColor: '#F0FDF4',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  applicationStatusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  applicationStatusText: {
    fontSize: 14,
    color: '#059669',
    fontWeight: '500',
    marginLeft: 8,
  },
  applicationStatusLabel: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 8,
    textTransform: 'capitalize',
  },
  coverLetterPreview: {
    marginTop: 8,
  },
  coverLetterLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 4,
  },
};

export const styles = StyleSheet.create({
  ...baseStyles,
  ...sections, // UPDATED: Now includes enhanced profile card and section header styles
  ...dashboard,
  ...cards,
  ...buttons,
  ...textBlocks,
  ...modals,
  ...notification,
  ...stateStyles,
});